[package]
name = "zk_campus_contract"
version = "0.1.0"
edition = "2021"

[dependencies]
# 添加Psy SDK核心依赖（根据官方文档调整版本）
psy-sdk = "0.1.0"
psy-storage = "0.1.0"  # 链上存储模块
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.3"  # 序列化存储数据